"""
Repository interfaces.

Defined as `typing.Protocol`s rather than ABCs: any object with the
right method shapes satisfies the interface structurally, with no
inheritance required. This is what lets `application/` services be
unit-tested against simple in-memory fakes (see `tests/fakes.py`)
without spinning up Postgres, while the real
`infrastructure/db/repositories/*` implementations satisfy the exact
same contract against SQLAlchemy.

Per SRS §10.1: `domain/` never imports SQLAlchemy, FastAPI, or anything
from `infrastructure/`.
"""

from __future__ import annotations

from datetime import datetime
from typing import Protocol
from uuid import UUID

from app.domain.entities import (
    Asset,
    AuditLogEntry,
    AuthorizationRecord,
    Finding,
    Organization,
    OrganizationInvitation,
    OrganizationMember,
    Project,
    ProjectMember,
    Scan,
    Session,
    Target,
    ToolResult,
    User,
)
from app.domain.value_objects import (
    AssetType,
    FindingStatus,
    OrganizationRole,
    ProjectRole,
    ScanStatus,
    Severity,
)


class UserRepository(Protocol):
    async def get_by_id(self, user_id: UUID) -> User | None: ...
    async def get_by_email(self, email: str) -> User | None: ...
    async def add(self, user: User) -> None: ...


class SessionRepository(Protocol):
    async def add(self, session: Session) -> None: ...
    async def get_by_id(self, session_id: UUID) -> Session | None: ...
    async def get_by_token_hash(self, token_hash: str) -> Session | None: ...
    async def revoke(self, session_id: UUID) -> None: ...
    async def revoke_all_for_user(self, user_id: UUID) -> None: ...


class OrganizationRepository(Protocol):
    async def get_by_id(self, organization_id: UUID) -> Organization | None: ...
    async def list_for_user(self, user_id: UUID) -> list[Organization]: ...
    async def add(self, organization: Organization) -> None: ...
    async def update(self, organization: Organization) -> None: ...
    async def soft_delete(self, organization_id: UUID) -> None: ...

    async def add_member(self, member: OrganizationMember) -> None: ...
    async def get_member(
        self, organization_id: UUID, user_id: UUID
    ) -> OrganizationMember | None: ...
    async def list_members(self, organization_id: UUID) -> list[OrganizationMember]: ...
    async def update_member_role(
        self, organization_id: UUID, user_id: UUID, role: OrganizationRole
    ) -> None: ...

    async def add_invitation(self, invitation: OrganizationInvitation) -> None: ...
    async def list_invitations(self, organization_id: UUID) -> list[OrganizationInvitation]: ...


class ProjectRepository(Protocol):
    async def get_by_id(self, project_id: UUID) -> Project | None: ...
    async def list_for_organization(self, organization_id: UUID) -> list[Project]: ...
    async def add(self, project: Project) -> None: ...
    async def update(self, project: Project) -> None: ...
    async def soft_delete(self, project_id: UUID) -> None: ...

    async def add_member(self, member: ProjectMember) -> None: ...
    async def get_member(self, project_id: UUID, user_id: UUID) -> ProjectMember | None: ...
    async def list_members(self, project_id: UUID) -> list[ProjectMember]: ...
    async def update_member_role(
        self, project_id: UUID, user_id: UUID, role: ProjectRole
    ) -> None: ...


class TargetRepository(Protocol):
    async def get_by_id(self, target_id: UUID) -> Target | None: ...
    async def list_for_project(self, project_id: UUID) -> list[Target]: ...
    async def add(self, target: Target) -> None: ...
    async def update(self, target: Target) -> None: ...
    async def soft_delete(self, target_id: UUID) -> None: ...


class AuthorizationRecordRepository(Protocol):
    async def get_by_id(self, record_id: UUID) -> AuthorizationRecord | None: ...
    async def get_active_for_project(
        self, project_id: UUID, on_date: datetime
    ) -> AuthorizationRecord | None: ...
    async def list_for_project(self, project_id: UUID) -> list[AuthorizationRecord]: ...
    async def add(self, record: AuthorizationRecord) -> None: ...


class AuditLogRepository(Protocol):
    async def add(self, entry: AuditLogEntry) -> None: ...
    async def list_for_organization(self, organization_id: UUID) -> list[AuditLogEntry]: ...


class ScanRepository(Protocol):
    """
    Milestone 3. `update_status`, `append_log`, `complete`, and `fail`
    are separate, narrow methods (rather than one generic `update`)
    because each corresponds to a distinct, meaningful lifecycle
    transition the ExecutionEngine performs — matching the milestone
    spec's explicit method list and keeping each call-site's intent
    self-evident at the call, not buried in a diff of arbitrary fields.
    """

    async def create(self, scan: Scan) -> None: ...
    async def get(self, scan_id: UUID) -> Scan | None: ...
    async def list(
        self, project_id: UUID, limit: int = 20, cursor: datetime | None = None
    ) -> list[Scan]: ...
    async def update_status(self, scan_id: UUID, status: ScanStatus) -> None: ...
    async def append_log(self, scan_id: UUID, logs_path: str) -> None: ...
    async def complete(self, scan_id: UUID, exit_code: int, artifacts_path: str | None) -> None: ...
    async def fail(self, scan_id: UUID, error_message: str, exit_code: int | None) -> None: ...


class ToolResultRepository(Protocol):
    async def add(self, tool_result: ToolResult) -> None: ...
    async def get(self, tool_result_id: UUID) -> ToolResult | None: ...
    async def list_for_scan(self, scan_id: UUID) -> list[ToolResult]: ...


class AssetRepository(Protocol):
    async def get_by_id(self, asset_id: UUID) -> Asset | None: ...
    async def list_for_project(
        self,
        project_id: UUID,
        asset_type: AssetType | None = None,
        limit: int = 20,
        cursor: datetime | None = None,
    ) -> list[Asset]: ...
    async def add(self, asset: Asset) -> None: ...
    async def update(self, asset: Asset) -> None: ...
    async def upsert(self, asset: Asset) -> Asset: ...
    async def get_by_dedup(
        self, project_id: UUID, asset_type: AssetType, value: str
    ) -> Asset | None: ...


class FindingRepository(Protocol):
    async def add(self, finding: Finding) -> None: ...
    async def get(self, finding_id: UUID) -> Finding | None: ...
    async def list_for_project(
        self,
        project_id: UUID,
        severity: Severity | None = None,
        limit: int = 20,
        cursor: datetime | None = None,
    ) -> list[Finding]: ...
    async def get_by_dedup_key(
        self, project_id: UUID, dedup_key: str
    ) -> Finding | None: ...
    async def update_status(self, finding_id: UUID, status: FindingStatus) -> None: ...
