"""
Repository interfaces.

Defined as `typing.Protocol`s rather than ABCs: any object with the
right method shapes satisfies the interface structurally, with no
inheritance required. This is what lets `application/` services be
unit-tested against simple in-memory fakes (see `tests/fakes.py`)
without spinning up Postgres, while the real
`infrastructure/db/repositories/*` implementations satisfy the exact
same contract against SQLAlchemy.

Per SRS §10.1: `domain/` never imports SQLAlchemy, FastAPI, or anything
from `infrastructure/`.
"""

from __future__ import annotations

from datetime import datetime
from typing import Protocol
from uuid import UUID

from app.domain.entities import (
    AuditLogEntry,
    AuthorizationRecord,
    Organization,
    OrganizationInvitation,
    OrganizationMember,
    Project,
    ProjectMember,
    Session,
    Target,
    User,
)
from app.domain.value_objects import OrganizationRole, ProjectRole


class UserRepository(Protocol):
    async def get_by_id(self, user_id: UUID) -> User | None: ...
    async def get_by_email(self, email: str) -> User | None: ...
    async def add(self, user: User) -> None: ...


class SessionRepository(Protocol):
    async def add(self, session: Session) -> None: ...
    async def get_by_id(self, session_id: UUID) -> Session | None: ...
    async def get_by_token_hash(self, token_hash: str) -> Session | None: ...
    async def revoke(self, session_id: UUID) -> None: ...
    async def revoke_all_for_user(self, user_id: UUID) -> None: ...


class OrganizationRepository(Protocol):
    async def get_by_id(self, organization_id: UUID) -> Organization | None: ...
    async def list_for_user(self, user_id: UUID) -> list[Organization]: ...
    async def add(self, organization: Organization) -> None: ...
    async def update(self, organization: Organization) -> None: ...
    async def soft_delete(self, organization_id: UUID) -> None: ...

    async def add_member(self, member: OrganizationMember) -> None: ...
    async def get_member(
        self, organization_id: UUID, user_id: UUID
    ) -> OrganizationMember | None: ...
    async def list_members(self, organization_id: UUID) -> list[OrganizationMember]: ...
    async def update_member_role(
        self, organization_id: UUID, user_id: UUID, role: OrganizationRole
    ) -> None: ...

    async def add_invitation(self, invitation: OrganizationInvitation) -> None: ...
    async def list_invitations(self, organization_id: UUID) -> list[OrganizationInvitation]: ...


class ProjectRepository(Protocol):
    async def get_by_id(self, project_id: UUID) -> Project | None: ...
    async def list_for_organization(self, organization_id: UUID) -> list[Project]: ...
    async def add(self, project: Project) -> None: ...
    async def update(self, project: Project) -> None: ...
    async def soft_delete(self, project_id: UUID) -> None: ...

    async def add_member(self, member: ProjectMember) -> None: ...
    async def get_member(self, project_id: UUID, user_id: UUID) -> ProjectMember | None: ...
    async def list_members(self, project_id: UUID) -> list[ProjectMember]: ...
    async def update_member_role(
        self, project_id: UUID, user_id: UUID, role: ProjectRole
    ) -> None: ...


class TargetRepository(Protocol):
    async def get_by_id(self, target_id: UUID) -> Target | None: ...
    async def list_for_project(self, project_id: UUID) -> list[Target]: ...
    async def add(self, target: Target) -> None: ...
    async def update(self, target: Target) -> None: ...
    async def soft_delete(self, target_id: UUID) -> None: ...


class AuthorizationRecordRepository(Protocol):
    async def get_by_id(self, record_id: UUID) -> AuthorizationRecord | None: ...
    async def get_active_for_project(
        self, project_id: UUID, on_date: datetime
    ) -> AuthorizationRecord | None: ...
    async def list_for_project(self, project_id: UUID) -> list[AuthorizationRecord]: ...
    async def add(self, record: AuthorizationRecord) -> None: ...


class AuditLogRepository(Protocol):
    async def add(self, entry: AuditLogEntry) -> None: ...
    async def list_for_organization(self, organization_id: UUID) -> list[AuditLogEntry]: ...
